// Generated by the protocol buffer compiler. DO NOT EDIT!
// clang-format off
// source: kv.proto

#import <Foundation/Foundation.h>
#import <GRPCClient/GRPCCall.h>
#import <ProtoRPC/ProtoRPC.h>
#import <RxLibrary/GRXWriter.h>

#import "Kv.pbobjc.h"

NS_ASSUME_NONNULL_BEGIN

@protocol KV <NSObject>

#pragma mark Get(GetRequest) returns (GetResponse)

- (void)getWithRequest:(GetRequest *)request handler:(void(^)(GetResponse *_Nullable response, NSError *_Nullable error))handler;
- (GRPCProtoCall *)RPCToGetWithRequest:(GetRequest *)request handler:(void(^)(GetResponse *_Nullable response, NSError *_Nullable error))handler;

#pragma mark Put(PutRequest) returns (Empty)

- (void)putWithRequest:(PutRequest *)request handler:(void(^)(Empty *_Nullable response, NSError *_Nullable error))handler;
- (GRPCProtoCall *)RPCToPutWithRequest:(PutRequest *)request handler:(void(^)(Empty *_Nullable response, NSError *_Nullable error))handler;

@end

/**
 * Basic service implementation, over gRPC, that only does
 * temporary marshalling and unmarshalling.
 */
@interface KV : GRPCProtoService<KV>

- (instancetype)initWithHost:(NSString *)host NS_DESIGNATED_INITIALIZER;

+ (instancetype)serviceWithHost:(NSString *)host;

@end

NS_ASSUME_NONNULL_END

// clang-format on
