// Generated by the protocol buffer compiler. DO NOT EDIT!
// clang-format off
// source: kv.proto

#import "Kv.pbobjc.h"

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - KVRoot

@implementation KVRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    registry = [[GPBExtensionRegistry alloc] init];
  }
  return registry;
}

@end

#pragma mark - GetRequest

@implementation GetRequest

@dynamic key;

typedef struct GetRequest__storage_ {
  uint32_t _has_storage_[1];
  NSString *key;
} GetRequest__storage_;

+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "key",
        .dataTypeSpecific.clazz = Nil,
        .number = GetRequest_FieldNumber_Key,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetRequest__storage_, key),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[GetRequest class]
                                              rootClass:[KVRoot class]
                                                   file:nil
                                                 fields:fields
                                             fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                            storageSize:sizeof(GetRequest__storage_)
                                                  flags:(GPBDescriptorInitializationFlags)0];
  }
  return descriptor;
}

@end

#pragma mark - GetResponse

@implementation GetResponse

@dynamic value;

typedef struct GetResponse__storage_ {
  uint32_t _has_storage_[1];
  NSData *value;
} GetResponse__storage_;

+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "value",
        .dataTypeSpecific.clazz = Nil,
        .number = GetResponse_FieldNumber_Value,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetResponse__storage_, value),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[GetResponse class]
                                              rootClass:[KVRoot class]
                                                   file:nil
                                                 fields:fields
                                             fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                            storageSize:sizeof(GetResponse__storage_)
                                                  flags:(GPBDescriptorInitializationFlags)0];
  }
  return descriptor;
}

@end

#pragma mark - PutRequest

@implementation PutRequest

@dynamic key;
@dynamic value;

typedef struct PutRequest__storage_ {
  uint32_t _has_storage_[1];
  NSString *key;
  NSData *value;
} PutRequest__storage_;

+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "key",
        .dataTypeSpecific.clazz = Nil,
        .number = PutRequest_FieldNumber_Key,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PutRequest__storage_, key),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "value",
        .dataTypeSpecific.clazz = Nil,
        .number = PutRequest_FieldNumber_Value,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PutRequest__storage_, value),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
    };
    descriptor = [GPBDescriptor allocDescriptorForClass:[PutRequest class]
                                              rootClass:[KVRoot class]
                                                   file:nil
                                                 fields:fields
                                             fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                            storageSize:sizeof(PutRequest__storage_)
                                                  flags:(GPBDescriptorInitializationFlags)0];
  }
  return descriptor;
}

@end

#pragma mark - Empty

@implementation Empty

typedef struct Empty__storage_ {
  uint32_t _has_storage_[1];
} Empty__storage_;

+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    descriptor = [GPBDescriptor allocDescriptorForClass:[Empty class]
                                              rootClass:[KVRoot class]
                                                   file:nil
                                                 fields:NULL
                                             fieldCount:0
                                            storageSize:sizeof(Empty__storage_)
                                                  flags:(GPBDescriptorInitializationFlags)0];
  }
  return descriptor;
}

@end

#pragma clang diagnostic pop

// clang-format on
