// Generated by the protocol buffer compiler. DO NOT EDIT!
// clang-format off
// source: kv.proto

#import <Foundation/Foundation.h>
#import <Protobuf/GPBProtocolBuffers.h>

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - KVRoot

@interface KVRoot : GPBRootObject
@end

#pragma mark - GetRequest

typedef GPB_ENUM(GetRequest_FieldNumber) {
  GetRequest_FieldNumber_Key = 1,
};

@interface GetRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

@end

#pragma mark - GetResponse

typedef GPB_ENUM(GetResponse_FieldNumber) {
  GetResponse_FieldNumber_Value = 1,
};

@interface GetResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *value;

@end

#pragma mark - PutRequest

typedef GPB_ENUM(PutRequest_FieldNumber) {
  PutRequest_FieldNumber_Key = 1,
  PutRequest_FieldNumber_Value = 2,
};

@interface PutRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;
@property(nonatomic, readwrite, copy, null_resettable) NSData *value;

@end

#pragma mark - Empty

@interface Empty : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// clang-format on
