// Generated by the protocol buffer compiler. DO NOT EDIT!
// clang-format off
// source: kv.proto

#import "Kv.pbrpc.h"
#import "Kv.pbobjc.h"

#import <ProtoRPC/ProtoRPCLegacy.h>
#import <RxLibrary/GRXWriter+Immediate.h>

static NSString *const kPackageName = @"proto";
static NSString *const kServiceName = @"KV";

@implementation KV

+ (instancetype)serviceWithHost:(NSString *)host {
  return [[self alloc] initWithHost:host];
}

- (instancetype)initWithHost:(NSString *)host {
  return (self = [super initWithHost:host packageName:kPackageName serviceName:kServiceName]);
}

#pragma mark Get(GetRequest) returns (GetResponse)

- (void)getWithRequest:(GetRequest *)request handler:(void(^)(GetResponse *_Nullable response, NSError *_Nullable error))handler {
  [[self RPCToGetWithRequest:request handler:handler] start];
}

- (GRPCProtoCall *)RPCToGetWithRequest:(GetRequest *)request handler:(void(^)(GetResponse *_Nullable response, NSError *_Nullable error))handler {
  return [self RPCToMethod:@"Get"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[GetResponse class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}

#pragma mark Put(PutRequest) returns (Empty)

- (void)putWithRequest:(PutRequest *)request handler:(void(^)(Empty *_Nullable response, NSError *_Nullable error))handler {
  [[self RPCToPutWithRequest:request handler:handler] start];
}

- (GRPCProtoCall *)RPCToPutWithRequest:(PutRequest *)request handler:(void(^)(Empty *_Nullable response, NSError *_Nullable error))handler {
  return [self RPCToMethod:@"Put"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[Empty class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}

@end

// clang-format on
