# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.celersql_pb2 as celersql__pb2

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in celersql_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimpleSQLStoreStub(object):
    """Service definition for interacting with a SimpleSQL database
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteQuery = channel.unary_stream(
                '/proto.SimpleSQLStore/ExecuteQuery',
                request_serializer=celersql__pb2.QueryRequest.SerializeToString,
                response_deserializer=celersql__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.CancelQuery = channel.unary_unary(
                '/proto.SimpleSQLStore/CancelQuery',
                request_serializer=celersql__pb2.CancelQueryRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ExecuteUpdate = channel.unary_unary(
                '/proto.SimpleSQLStore/ExecuteUpdate',
                request_serializer=celersql__pb2.UpdateRequest.SerializeToString,
                response_deserializer=celersql__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.BatchExecute = channel.unary_unary(
                '/proto.SimpleSQLStore/BatchExecute',
                request_serializer=celersql__pb2.BatchRequest.SerializeToString,
                response_deserializer=celersql__pb2.BatchResponse.FromString,
                _registered_method=True)
        self.ExecuteBulkInsert = channel.unary_unary(
                '/proto.SimpleSQLStore/ExecuteBulkInsert',
                request_serializer=celersql__pb2.BulkInsertRequest.SerializeToString,
                response_deserializer=celersql__pb2.BulkInsertResponse.FromString,
                _registered_method=True)
        self.GetSchema = channel.unary_unary(
                '/proto.SimpleSQLStore/GetSchema',
                request_serializer=celersql__pb2.SchemaRequest.SerializeToString,
                response_deserializer=celersql__pb2.SchemaResponse.FromString,
                _registered_method=True)
        self.ExplainQueryPlan = channel.unary_unary(
                '/proto.SimpleSQLStore/ExplainQueryPlan',
                request_serializer=celersql__pb2.ExplainQueryRequest.SerializeToString,
                response_deserializer=celersql__pb2.ExplainQueryResponse.FromString,
                _registered_method=True)
        self.VacuumDatabase = channel.unary_unary(
                '/proto.SimpleSQLStore/VacuumDatabase',
                request_serializer=celersql__pb2.VacuumRequest.SerializeToString,
                response_deserializer=celersql__pb2.VacuumResponse.FromString,
                _registered_method=True)
        self.BackupDatabase = channel.unary_unary(
                '/proto.SimpleSQLStore/BackupDatabase',
                request_serializer=celersql__pb2.BackupRequest.SerializeToString,
                response_deserializer=celersql__pb2.BackupResponse.FromString,
                _registered_method=True)
        self.CheckIntegrity = channel.unary_unary(
                '/proto.SimpleSQLStore/CheckIntegrity',
                request_serializer=celersql__pb2.IntegrityRequest.SerializeToString,
                response_deserializer=celersql__pb2.IntegrityResponse.FromString,
                _registered_method=True)
        self.GetDatabaseInfo = channel.unary_unary(
                '/proto.SimpleSQLStore/GetDatabaseInfo',
                request_serializer=celersql__pb2.DatabaseInfoRequest.SerializeToString,
                response_deserializer=celersql__pb2.DatabaseInfoResponse.FromString,
                _registered_method=True)
        self.CreateTable = channel.unary_unary(
                '/proto.SimpleSQLStore/CreateTable',
                request_serializer=celersql__pb2.CreateTableRequest.SerializeToString,
                response_deserializer=celersql__pb2.CreateTableResponse.FromString,
                _registered_method=True)
        self.DropTable = channel.unary_unary(
                '/proto.SimpleSQLStore/DropTable',
                request_serializer=celersql__pb2.DropTableRequest.SerializeToString,
                response_deserializer=celersql__pb2.DropTableResponse.FromString,
                _registered_method=True)
        self.ListTables = channel.unary_unary(
                '/proto.SimpleSQLStore/ListTables',
                request_serializer=celersql__pb2.ListTablesRequest.SerializeToString,
                response_deserializer=celersql__pb2.ListTablesResponse.FromString,
                _registered_method=True)
        self.AlterTable = channel.unary_unary(
                '/proto.SimpleSQLStore/AlterTable',
                request_serializer=celersql__pb2.AlterTableRequest.SerializeToString,
                response_deserializer=celersql__pb2.AlterTableResponse.FromString,
                _registered_method=True)
        self.CreateIndex = channel.unary_unary(
                '/proto.SimpleSQLStore/CreateIndex',
                request_serializer=celersql__pb2.CreateIndexRequest.SerializeToString,
                response_deserializer=celersql__pb2.CreateIndexResponse.FromString,
                _registered_method=True)
        self.DropIndex = channel.unary_unary(
                '/proto.SimpleSQLStore/DropIndex',
                request_serializer=celersql__pb2.DropIndexRequest.SerializeToString,
                response_deserializer=celersql__pb2.DropIndexResponse.FromString,
                _registered_method=True)
        self.ListIndexes = channel.unary_unary(
                '/proto.SimpleSQLStore/ListIndexes',
                request_serializer=celersql__pb2.ListIndexesRequest.SerializeToString,
                response_deserializer=celersql__pb2.ListIndexesResponse.FromString,
                _registered_method=True)
        self.GetConnectionPoolStats = channel.unary_unary(
                '/proto.SimpleSQLStore/GetConnectionPoolStats',
                request_serializer=celersql__pb2.ConnectionPoolStatsRequest.SerializeToString,
                response_deserializer=celersql__pb2.ConnectionPoolStatsResponse.FromString,
                _registered_method=True)
        self.SetConnectionPoolSize = channel.unary_unary(
                '/proto.SimpleSQLStore/SetConnectionPoolSize',
                request_serializer=celersql__pb2.ConnectionPoolSizeRequest.SerializeToString,
                response_deserializer=celersql__pb2.ConnectionPoolSizeResponse.FromString,
                _registered_method=True)
        self.PrepareStatement = channel.unary_unary(
                '/proto.SimpleSQLStore/PrepareStatement',
                request_serializer=celersql__pb2.PrepareStatementRequest.SerializeToString,
                response_deserializer=celersql__pb2.PrepareStatementResponse.FromString,
                _registered_method=True)
        self.ExecutePreparedStatement = channel.unary_stream(
                '/proto.SimpleSQLStore/ExecutePreparedStatement',
                request_serializer=celersql__pb2.ExecutePreparedStatementRequest.SerializeToString,
                response_deserializer=celersql__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.DeletePreparedStatement = channel.unary_unary(
                '/proto.SimpleSQLStore/DeletePreparedStatement',
                request_serializer=celersql__pb2.DeletePreparedStatementRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.BeginTransaction = channel.unary_unary(
                '/proto.SimpleSQLStore/BeginTransaction',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=celersql__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.CommitTransaction = channel.unary_unary(
                '/proto.SimpleSQLStore/CommitTransaction',
                request_serializer=celersql__pb2.TransactionRequest.SerializeToString,
                response_deserializer=celersql__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.RollbackTransaction = channel.unary_unary(
                '/proto.SimpleSQLStore/RollbackTransaction',
                request_serializer=celersql__pb2.TransactionRequest.SerializeToString,
                response_deserializer=celersql__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.GetTransactionState = channel.unary_unary(
                '/proto.SimpleSQLStore/GetTransactionState',
                request_serializer=celersql__pb2.GetTransactionStateRequest.SerializeToString,
                response_deserializer=celersql__pb2.GetTransactionStateResponse.FromString,
                _registered_method=True)
        self.CreateConnection = channel.unary_unary(
                '/proto.SimpleSQLStore/CreateConnection',
                request_serializer=celersql__pb2.ConnectionRequest.SerializeToString,
                response_deserializer=celersql__pb2.ConnectionResponse.FromString,
                _registered_method=True)
        self.CloseConnection = channel.unary_unary(
                '/proto.SimpleSQLStore/CloseConnection',
                request_serializer=celersql__pb2.ConnectionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class SimpleSQLStoreServicer(object):
    """Service definition for interacting with a SimpleSQL database
    """

    def ExecuteQuery(self, request, context):
        """Executes a SQL query and streams the results back to the client.
        This RPC is suitable for queries that may return a large number of rows.
        The server will send a stream of QueryResponse messages, each containing
        a subset of the result rows. The final QueryResponse message will contain
        the overall status of the query execution.

        Example Usage:
        Client: ExecuteQuery(QueryRequest{ connection_id: "conn1", query: "SELECT * FROM large_table" })
        Server: (streams multiple QueryResponse messages with row data)
        Server: QueryResponse{ status: Status{ code: OK, message: "" } }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelQuery(self, request, context):
        """Cancels an ongoing query.

        The client must provide the connection ID and the query ID of the query to cancel.
        The query ID should be obtained from the initial QueryResponse message
        returned by ExecuteQuery.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteUpdate(self, request, context):
        """Executes an update SQL statement (e.g., INSERT, UPDATE, DELETE).
        Returns the number of rows affected and the ID of the last inserted row (if applicable).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchExecute(self, request, context):
        """Executes multiple queries or updates in a single batch.
        Each query or update can have its own parameters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteBulkInsert(self, request, context):
        """Performs bulk inserts into a table, optimizing for large data loads.
        The client provides the table name, columns, and rows to insert.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchema(self, request, context):
        """Retrieves schema details for a specific table.

        Example Usage:
        Client: GetSchema(SchemaRequest{ connection_id: "conn1", table_name: "users" })
        Server: SchemaResponse{ columns: [...], status: Status{ code: OK, message: "" } }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainQueryPlan(self, request, context):
        """Provides the query plan for debugging and optimization purposes.
        The client sends a SQL query, and the server responds with the execution plan steps.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VacuumDatabase(self, request, context):
        """Performs database vacuum to optimize the database by cleaning up unused spaces.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BackupDatabase(self, request, context):
        """Creates a backup of the database.
        The client specifies the path where the backup should be stored.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckIntegrity(self, request, context):
        """Checks the integrity of the database.
        This ensures that the database is not corrupted and is in a consistent state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatabaseInfo(self, request, context):
        """Retrieves metadata about the database, such as size, page count, and database version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTable(self, request, context):
        """Table management
        Create a new table
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropTable(self, request, context):
        """Drop an existing table
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTables(self, request, context):
        """List all tables
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlterTable(self, request, context):
        """Alter a table structure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIndex(self, request, context):
        """Index management
        Create a new index
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropIndex(self, request, context):
        """Drop an existing index
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIndexes(self, request, context):
        """List all indexes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConnectionPoolStats(self, request, context):
        """Connection pool management
        Get connection pool statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConnectionPoolSize(self, request, context):
        """Set the connection pool size
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareStatement(self, request, context):
        """Statement preparation and execution
        Prepare a SQL statement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutePreparedStatement(self, request, context):
        """Execute a prepared statement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePreparedStatement(self, request, context):
        """Clean up prepared statement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginTransaction(self, request, context):
        """Transaction management
        Start a new transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitTransaction(self, request, context):
        """Commit the active transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackTransaction(self, request, context):
        """Rollback the active transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionState(self, request, context):
        """Get the current transaction state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateConnection(self, request, context):
        """Connection management
        Establish a new connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseConnection(self, request, context):
        """Close an active connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimpleSQLStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteQuery,
                    request_deserializer=celersql__pb2.QueryRequest.FromString,
                    response_serializer=celersql__pb2.QueryResponse.SerializeToString,
            ),
            'CancelQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelQuery,
                    request_deserializer=celersql__pb2.CancelQueryRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ExecuteUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteUpdate,
                    request_deserializer=celersql__pb2.UpdateRequest.FromString,
                    response_serializer=celersql__pb2.UpdateResponse.SerializeToString,
            ),
            'BatchExecute': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchExecute,
                    request_deserializer=celersql__pb2.BatchRequest.FromString,
                    response_serializer=celersql__pb2.BatchResponse.SerializeToString,
            ),
            'ExecuteBulkInsert': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteBulkInsert,
                    request_deserializer=celersql__pb2.BulkInsertRequest.FromString,
                    response_serializer=celersql__pb2.BulkInsertResponse.SerializeToString,
            ),
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=celersql__pb2.SchemaRequest.FromString,
                    response_serializer=celersql__pb2.SchemaResponse.SerializeToString,
            ),
            'ExplainQueryPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainQueryPlan,
                    request_deserializer=celersql__pb2.ExplainQueryRequest.FromString,
                    response_serializer=celersql__pb2.ExplainQueryResponse.SerializeToString,
            ),
            'VacuumDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.VacuumDatabase,
                    request_deserializer=celersql__pb2.VacuumRequest.FromString,
                    response_serializer=celersql__pb2.VacuumResponse.SerializeToString,
            ),
            'BackupDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.BackupDatabase,
                    request_deserializer=celersql__pb2.BackupRequest.FromString,
                    response_serializer=celersql__pb2.BackupResponse.SerializeToString,
            ),
            'CheckIntegrity': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckIntegrity,
                    request_deserializer=celersql__pb2.IntegrityRequest.FromString,
                    response_serializer=celersql__pb2.IntegrityResponse.SerializeToString,
            ),
            'GetDatabaseInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatabaseInfo,
                    request_deserializer=celersql__pb2.DatabaseInfoRequest.FromString,
                    response_serializer=celersql__pb2.DatabaseInfoResponse.SerializeToString,
            ),
            'CreateTable': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTable,
                    request_deserializer=celersql__pb2.CreateTableRequest.FromString,
                    response_serializer=celersql__pb2.CreateTableResponse.SerializeToString,
            ),
            'DropTable': grpc.unary_unary_rpc_method_handler(
                    servicer.DropTable,
                    request_deserializer=celersql__pb2.DropTableRequest.FromString,
                    response_serializer=celersql__pb2.DropTableResponse.SerializeToString,
            ),
            'ListTables': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTables,
                    request_deserializer=celersql__pb2.ListTablesRequest.FromString,
                    response_serializer=celersql__pb2.ListTablesResponse.SerializeToString,
            ),
            'AlterTable': grpc.unary_unary_rpc_method_handler(
                    servicer.AlterTable,
                    request_deserializer=celersql__pb2.AlterTableRequest.FromString,
                    response_serializer=celersql__pb2.AlterTableResponse.SerializeToString,
            ),
            'CreateIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIndex,
                    request_deserializer=celersql__pb2.CreateIndexRequest.FromString,
                    response_serializer=celersql__pb2.CreateIndexResponse.SerializeToString,
            ),
            'DropIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.DropIndex,
                    request_deserializer=celersql__pb2.DropIndexRequest.FromString,
                    response_serializer=celersql__pb2.DropIndexResponse.SerializeToString,
            ),
            'ListIndexes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIndexes,
                    request_deserializer=celersql__pb2.ListIndexesRequest.FromString,
                    response_serializer=celersql__pb2.ListIndexesResponse.SerializeToString,
            ),
            'GetConnectionPoolStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectionPoolStats,
                    request_deserializer=celersql__pb2.ConnectionPoolStatsRequest.FromString,
                    response_serializer=celersql__pb2.ConnectionPoolStatsResponse.SerializeToString,
            ),
            'SetConnectionPoolSize': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConnectionPoolSize,
                    request_deserializer=celersql__pb2.ConnectionPoolSizeRequest.FromString,
                    response_serializer=celersql__pb2.ConnectionPoolSizeResponse.SerializeToString,
            ),
            'PrepareStatement': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareStatement,
                    request_deserializer=celersql__pb2.PrepareStatementRequest.FromString,
                    response_serializer=celersql__pb2.PrepareStatementResponse.SerializeToString,
            ),
            'ExecutePreparedStatement': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecutePreparedStatement,
                    request_deserializer=celersql__pb2.ExecutePreparedStatementRequest.FromString,
                    response_serializer=celersql__pb2.QueryResponse.SerializeToString,
            ),
            'DeletePreparedStatement': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePreparedStatement,
                    request_deserializer=celersql__pb2.DeletePreparedStatementRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'BeginTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginTransaction,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=celersql__pb2.TransactionResponse.SerializeToString,
            ),
            'CommitTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitTransaction,
                    request_deserializer=celersql__pb2.TransactionRequest.FromString,
                    response_serializer=celersql__pb2.TransactionResponse.SerializeToString,
            ),
            'RollbackTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackTransaction,
                    request_deserializer=celersql__pb2.TransactionRequest.FromString,
                    response_serializer=celersql__pb2.TransactionResponse.SerializeToString,
            ),
            'GetTransactionState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionState,
                    request_deserializer=celersql__pb2.GetTransactionStateRequest.FromString,
                    response_serializer=celersql__pb2.GetTransactionStateResponse.SerializeToString,
            ),
            'CreateConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConnection,
                    request_deserializer=celersql__pb2.ConnectionRequest.FromString,
                    response_serializer=celersql__pb2.ConnectionResponse.SerializeToString,
            ),
            'CloseConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseConnection,
                    request_deserializer=celersql__pb2.ConnectionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.SimpleSQLStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.SimpleSQLStore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimpleSQLStore(object):
    """Service definition for interacting with a SimpleSQL database
    """

    @staticmethod
    def ExecuteQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.SimpleSQLStore/ExecuteQuery',
            celersql__pb2.QueryRequest.SerializeToString,
            celersql__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/CancelQuery',
            celersql__pb2.CancelQueryRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/ExecuteUpdate',
            celersql__pb2.UpdateRequest.SerializeToString,
            celersql__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchExecute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/BatchExecute',
            celersql__pb2.BatchRequest.SerializeToString,
            celersql__pb2.BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteBulkInsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/ExecuteBulkInsert',
            celersql__pb2.BulkInsertRequest.SerializeToString,
            celersql__pb2.BulkInsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/GetSchema',
            celersql__pb2.SchemaRequest.SerializeToString,
            celersql__pb2.SchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainQueryPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/ExplainQueryPlan',
            celersql__pb2.ExplainQueryRequest.SerializeToString,
            celersql__pb2.ExplainQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VacuumDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/VacuumDatabase',
            celersql__pb2.VacuumRequest.SerializeToString,
            celersql__pb2.VacuumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BackupDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/BackupDatabase',
            celersql__pb2.BackupRequest.SerializeToString,
            celersql__pb2.BackupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckIntegrity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/CheckIntegrity',
            celersql__pb2.IntegrityRequest.SerializeToString,
            celersql__pb2.IntegrityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDatabaseInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/GetDatabaseInfo',
            celersql__pb2.DatabaseInfoRequest.SerializeToString,
            celersql__pb2.DatabaseInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/CreateTable',
            celersql__pb2.CreateTableRequest.SerializeToString,
            celersql__pb2.CreateTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/DropTable',
            celersql__pb2.DropTableRequest.SerializeToString,
            celersql__pb2.DropTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/ListTables',
            celersql__pb2.ListTablesRequest.SerializeToString,
            celersql__pb2.ListTablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AlterTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/AlterTable',
            celersql__pb2.AlterTableRequest.SerializeToString,
            celersql__pb2.AlterTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/CreateIndex',
            celersql__pb2.CreateIndexRequest.SerializeToString,
            celersql__pb2.CreateIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/DropIndex',
            celersql__pb2.DropIndexRequest.SerializeToString,
            celersql__pb2.DropIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIndexes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/ListIndexes',
            celersql__pb2.ListIndexesRequest.SerializeToString,
            celersql__pb2.ListIndexesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConnectionPoolStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/GetConnectionPoolStats',
            celersql__pb2.ConnectionPoolStatsRequest.SerializeToString,
            celersql__pb2.ConnectionPoolStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConnectionPoolSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/SetConnectionPoolSize',
            celersql__pb2.ConnectionPoolSizeRequest.SerializeToString,
            celersql__pb2.ConnectionPoolSizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareStatement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/PrepareStatement',
            celersql__pb2.PrepareStatementRequest.SerializeToString,
            celersql__pb2.PrepareStatementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecutePreparedStatement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.SimpleSQLStore/ExecutePreparedStatement',
            celersql__pb2.ExecutePreparedStatementRequest.SerializeToString,
            celersql__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePreparedStatement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/DeletePreparedStatement',
            celersql__pb2.DeletePreparedStatementRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/BeginTransaction',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            celersql__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/CommitTransaction',
            celersql__pb2.TransactionRequest.SerializeToString,
            celersql__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/RollbackTransaction',
            celersql__pb2.TransactionRequest.SerializeToString,
            celersql__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/GetTransactionState',
            celersql__pb2.GetTransactionStateRequest.SerializeToString,
            celersql__pb2.GetTransactionStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/CreateConnection',
            celersql__pb2.ConnectionRequest.SerializeToString,
            celersql__pb2.ConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/CloseConnection',
            celersql__pb2.ConnectionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
