# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.sqlite_pb2 import sqlite_pb2 as sqlite__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sqlite_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SQLiteStoreStub(object):
    """Service definition for interacting with an SQLite database
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteQuery = channel.unary_unary(
                '/proto.SQLiteStore/ExecuteQuery',
                request_serializer=sqlite__pb2.QueryRequest.SerializeToString,
                response_deserializer=sqlite__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.ExecuteUpdate = channel.unary_unary(
                '/proto.SQLiteStore/ExecuteUpdate',
                request_serializer=sqlite__pb2.UpdateRequest.SerializeToString,
                response_deserializer=sqlite__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.BatchExecute = channel.unary_unary(
                '/proto.SQLiteStore/BatchExecute',
                request_serializer=sqlite__pb2.BatchRequest.SerializeToString,
                response_deserializer=sqlite__pb2.BatchResponse.FromString,
                _registered_method=True)
        self.GetSchema = channel.unary_unary(
                '/proto.SQLiteStore/GetSchema',
                request_serializer=sqlite__pb2.SchemaRequest.SerializeToString,
                response_deserializer=sqlite__pb2.SchemaResponse.FromString,
                _registered_method=True)
        self.PrepareStatement = channel.unary_unary(
                '/proto.SQLiteStore/PrepareStatement',
                request_serializer=sqlite__pb2.PrepareStatementRequest.SerializeToString,
                response_deserializer=sqlite__pb2.PrepareStatementResponse.FromString,
                _registered_method=True)
        self.ExecutePreparedStatement = channel.unary_unary(
                '/proto.SQLiteStore/ExecutePreparedStatement',
                request_serializer=sqlite__pb2.ExecutePreparedStatementRequest.SerializeToString,
                response_deserializer=sqlite__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.BeginTransaction = channel.unary_unary(
                '/proto.SQLiteStore/BeginTransaction',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=sqlite__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.CommitTransaction = channel.unary_unary(
                '/proto.SQLiteStore/CommitTransaction',
                request_serializer=sqlite__pb2.TransactionRequest.SerializeToString,
                response_deserializer=sqlite__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.RollbackTransaction = channel.unary_unary(
                '/proto.SQLiteStore/RollbackTransaction',
                request_serializer=sqlite__pb2.TransactionRequest.SerializeToString,
                response_deserializer=sqlite__pb2.TransactionResponse.FromString,
                _registered_method=True)


class SQLiteStoreServicer(object):
    """Service definition for interacting with an SQLite database
    """

    def ExecuteQuery(self, request, context):
        """Query execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchExecute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareStatement(self, request, context):
        """Statement preparation and execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutePreparedStatement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginTransaction(self, request, context):
        """Transaction management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SQLiteStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteQuery,
                    request_deserializer=sqlite__pb2.QueryRequest.FromString,
                    response_serializer=sqlite__pb2.QueryResponse.SerializeToString,
            ),
            'ExecuteUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteUpdate,
                    request_deserializer=sqlite__pb2.UpdateRequest.FromString,
                    response_serializer=sqlite__pb2.UpdateResponse.SerializeToString,
            ),
            'BatchExecute': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchExecute,
                    request_deserializer=sqlite__pb2.BatchRequest.FromString,
                    response_serializer=sqlite__pb2.BatchResponse.SerializeToString,
            ),
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=sqlite__pb2.SchemaRequest.FromString,
                    response_serializer=sqlite__pb2.SchemaResponse.SerializeToString,
            ),
            'PrepareStatement': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareStatement,
                    request_deserializer=sqlite__pb2.PrepareStatementRequest.FromString,
                    response_serializer=sqlite__pb2.PrepareStatementResponse.SerializeToString,
            ),
            'ExecutePreparedStatement': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutePreparedStatement,
                    request_deserializer=sqlite__pb2.ExecutePreparedStatementRequest.FromString,
                    response_serializer=sqlite__pb2.QueryResponse.SerializeToString,
            ),
            'BeginTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginTransaction,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=sqlite__pb2.TransactionResponse.SerializeToString,
            ),
            'CommitTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitTransaction,
                    request_deserializer=sqlite__pb2.TransactionRequest.FromString,
                    response_serializer=sqlite__pb2.TransactionResponse.SerializeToString,
            ),
            'RollbackTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackTransaction,
                    request_deserializer=sqlite__pb2.TransactionRequest.FromString,
                    response_serializer=sqlite__pb2.TransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.SQLiteStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.SQLiteStore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SQLiteStore(object):
    """Service definition for interacting with an SQLite database
    """

    @staticmethod
    def ExecuteQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SQLiteStore/ExecuteQuery',
            sqlite__pb2.QueryRequest.SerializeToString,
            sqlite__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SQLiteStore/ExecuteUpdate',
            sqlite__pb2.UpdateRequest.SerializeToString,
            sqlite__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchExecute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SQLiteStore/BatchExecute',
            sqlite__pb2.BatchRequest.SerializeToString,
            sqlite__pb2.BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SQLiteStore/GetSchema',
            sqlite__pb2.SchemaRequest.SerializeToString,
            sqlite__pb2.SchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareStatement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SQLiteStore/PrepareStatement',
            sqlite__pb2.PrepareStatementRequest.SerializeToString,
            sqlite__pb2.PrepareStatementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecutePreparedStatement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SQLiteStore/ExecutePreparedStatement',
            sqlite__pb2.ExecutePreparedStatementRequest.SerializeToString,
            sqlite__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SQLiteStore/BeginTransaction',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sqlite__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SQLiteStore/CommitTransaction',
            sqlite__pb2.TransactionRequest.SerializeToString,
            sqlite__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SQLiteStore/RollbackTransaction',
            sqlite__pb2.TransactionRequest.SerializeToString,
            sqlite__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
