# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sqlite.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'sqlite.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csqlite.proto\x12\x05proto\"?\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12 \n\x06params\x18\x02 \x03(\x0b\x32\x10.proto.Parameter\"\x84\x01\n\tParameter\x12\x13\n\tint_value\x18\x01 \x01(\x03H\x00\x12\x15\n\x0b\x66loat_value\x18\x02 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x03 \x01(\tH\x00\x12\x14\n\nblob_value\x18\x04 \x01(\x0cH\x00\x12\x14\n\nnull_value\x18\x05 \x01(\x08H\x00\x42\x07\n\x05value\"o\n\rQueryResponse\x12\x1b\n\x04rows\x18\x01 \x03(\x0b\x32\r.proto.RowSet\x12\x14\n\x0c\x63olumn_names\x18\x02 \x03(\t\x12\x14\n\x0c\x63olumn_types\x18\x03 \x03(\t\x12\x15\n\rrows_affected\x18\x04 \x01(\x05\"*\n\x06RowSet\x12 \n\x06values\x18\x01 \x03(\x0b\x32\x10.proto.Parameter\"@\n\rUpdateRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12 \n\x06params\x18\x02 \x03(\x0b\x32\x10.proto.Parameter\"?\n\x0eUpdateResponse\x12\x15\n\rrows_affected\x18\x01 \x01(\x05\x12\x16\n\x0elast_insert_id\x18\x02 \x01(\x03\"4\n\x0c\x42\x61tchRequest\x12$\n\x07queries\x18\x01 \x03(\x0b\x32\x13.proto.QueryRequest\"6\n\rBatchResponse\x12%\n\x07results\x18\x01 \x03(\x0b\x32\x14.proto.QueryResponse\"#\n\rSchemaRequest\x12\x12\n\ntable_name\x18\x01 \x01(\t\"4\n\x0eSchemaResponse\x12\"\n\x07\x63olumns\x18\x01 \x03(\x0b\x32\x11.proto.ColumnInfo\"O\n\nColumnInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x10\n\x08nullable\x18\x03 \x01(\x08\x12\x13\n\x0bprimary_key\x18\x04 \x01(\x08\x32\xfb\x01\n\x0bSQLiteStore\x12\x39\n\x0c\x45xecuteQuery\x12\x13.proto.QueryRequest\x1a\x14.proto.QueryResponse\x12<\n\rExecuteUpdate\x12\x14.proto.UpdateRequest\x1a\x15.proto.UpdateResponse\x12\x39\n\x0c\x42\x61tchExecute\x12\x13.proto.BatchRequest\x1a\x14.proto.BatchResponse\x12\x38\n\tGetSchema\x12\x14.proto.SchemaRequest\x1a\x15.proto.SchemaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sqlite_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=23
  _globals['_QUERYREQUEST']._serialized_end=86
  _globals['_PARAMETER']._serialized_start=89
  _globals['_PARAMETER']._serialized_end=221
  _globals['_QUERYRESPONSE']._serialized_start=223
  _globals['_QUERYRESPONSE']._serialized_end=334
  _globals['_ROWSET']._serialized_start=336
  _globals['_ROWSET']._serialized_end=378
  _globals['_UPDATEREQUEST']._serialized_start=380
  _globals['_UPDATEREQUEST']._serialized_end=444
  _globals['_UPDATERESPONSE']._serialized_start=446
  _globals['_UPDATERESPONSE']._serialized_end=509
  _globals['_BATCHREQUEST']._serialized_start=511
  _globals['_BATCHREQUEST']._serialized_end=563
  _globals['_BATCHRESPONSE']._serialized_start=565
  _globals['_BATCHRESPONSE']._serialized_end=619
  _globals['_SCHEMAREQUEST']._serialized_start=621
  _globals['_SCHEMAREQUEST']._serialized_end=656
  _globals['_SCHEMARESPONSE']._serialized_start=658
  _globals['_SCHEMARESPONSE']._serialized_end=710
  _globals['_COLUMNINFO']._serialized_start=712
  _globals['_COLUMNINFO']._serialized_end=791
  _globals['_SQLITESTORE']._serialized_start=794
  _globals['_SQLITESTORE']._serialized_end=1045
# @@protoc_insertion_point(module_scope)
