<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv.proto

namespace GPBMetadata;

class Kv
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x95\x02\x0A\x08kv.proto\x12\x05proto\"\x19\x0A\x0AGetRequest\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\"\x1C\x0A\x0BGetResponse\x12\x0D\x0A\x05value\x18\x01 \x01(\x0C\"(\x0A\x0APutRequest\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x01(\x0C\"\x07\x0A\x05Empty2Z\x0A\x02KV\x12,\x0A\x03Get\x12\x11.proto.GetRequest\x1A\x12.proto.GetResponse\x12&\x0A\x03Put\x12\x11.proto.PutRequest\x1A\x0C.proto.EmptyB2Z0github.com/livingstaccato/grpc-kv-examples/protob\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

