// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: kv.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - proto.KV

/// Namespace containing generated types for the "proto.KV" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Proto_KV: Sendable {
    /// Service descriptor for the "proto.KV" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.KV")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "Get" metadata.
        public enum Get: Sendable {
            /// Request type for "Get".
            public typealias Input = Proto_GetRequest
            /// Response type for "Get".
            public typealias Output = Proto_GetResponse
            /// Descriptor for "Get".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.KV"),
                method: "Get"
            )
        }
        /// Namespace for "Put" metadata.
        public enum Put: Sendable {
            /// Request type for "Put".
            public typealias Input = Proto_PutRequest
            /// Response type for "Put".
            public typealias Output = Proto_Empty
            /// Descriptor for "Put".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.KV"),
                method: "Put"
            )
        }
        /// Descriptors for all methods in the "proto.KV" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Get.descriptor,
            Put.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "proto.KV" service.
    public static let proto_KV = GRPCCore.ServiceDescriptor(fullyQualifiedService: "proto.KV")
}

// MARK: proto.KV (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Proto_KV {
    /// Streaming variant of the service protocol for the "proto.KV" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "Get" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Proto_GetRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Proto_GetResponse` messages.
        func get(
            request: GRPCCore.StreamingServerRequest<Proto_GetRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Proto_GetResponse>

        /// Handle the "Put" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Proto_PutRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Proto_Empty` messages.
        func put(
            request: GRPCCore.StreamingServerRequest<Proto_PutRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Proto_Empty>
    }

    /// Service protocol for the "proto.KV" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Proto_KV.StreamingServiceProtocol {
        /// Handle the "Get" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Proto_GetRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Proto_GetResponse` message.
        func get(
            request: GRPCCore.ServerRequest<Proto_GetRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Proto_GetResponse>

        /// Handle the "Put" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Proto_PutRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Proto_Empty` message.
        func put(
            request: GRPCCore.ServerRequest<Proto_PutRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Proto_Empty>
    }

    /// Simple service protocol for the "proto.KV" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Proto_KV.ServiceProtocol {
        /// Handle the "Get" method.
        ///
        /// - Parameters:
        ///   - request: A `Proto_GetRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Proto_GetResponse` to respond with.
        func get(
            request: Proto_GetRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Proto_GetResponse

        /// Handle the "Put" method.
        ///
        /// - Parameters:
        ///   - request: A `Proto_PutRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Proto_Empty` to respond with.
        func put(
            request: Proto_PutRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Proto_Empty
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Proto_KV.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Proto_KV.Method.Get.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Proto_GetRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Proto_GetResponse>(),
            handler: { request, context in
                try await self.get(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Proto_KV.Method.Put.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Proto_PutRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Proto_Empty>(),
            handler: { request, context in
                try await self.put(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Proto_KV.ServiceProtocol {
    public func get(
        request: GRPCCore.StreamingServerRequest<Proto_GetRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Proto_GetResponse> {
        let response = try await self.get(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func put(
        request: GRPCCore.StreamingServerRequest<Proto_PutRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Proto_Empty> {
        let response = try await self.put(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Proto_KV.SimpleServiceProtocol {
    public func get(
        request: GRPCCore.ServerRequest<Proto_GetRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Proto_GetResponse> {
        return GRPCCore.ServerResponse<Proto_GetResponse>(
            message: try await self.get(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func put(
        request: GRPCCore.ServerRequest<Proto_PutRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Proto_Empty> {
        return GRPCCore.ServerResponse<Proto_Empty>(
            message: try await self.put(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: proto.KV (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Proto_KV {
    /// Generated client protocol for the "proto.KV" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "Get" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Proto_GetRequest` message.
        ///   - serializer: A serializer for `Proto_GetRequest` messages.
        ///   - deserializer: A deserializer for `Proto_GetResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func get<Result>(
            request: GRPCCore.ClientRequest<Proto_GetRequest>,
            serializer: some GRPCCore.MessageSerializer<Proto_GetRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Proto_GetResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Proto_GetResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Put" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Proto_PutRequest` message.
        ///   - serializer: A serializer for `Proto_PutRequest` messages.
        ///   - deserializer: A deserializer for `Proto_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func put<Result>(
            request: GRPCCore.ClientRequest<Proto_PutRequest>,
            serializer: some GRPCCore.MessageSerializer<Proto_PutRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Proto_Empty>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Proto_Empty>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "proto.KV" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Get" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Proto_GetRequest` message.
        ///   - serializer: A serializer for `Proto_GetRequest` messages.
        ///   - deserializer: A deserializer for `Proto_GetResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func get<Result>(
            request: GRPCCore.ClientRequest<Proto_GetRequest>,
            serializer: some GRPCCore.MessageSerializer<Proto_GetRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Proto_GetResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Proto_GetResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Proto_KV.Method.Get.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Put" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Proto_PutRequest` message.
        ///   - serializer: A serializer for `Proto_PutRequest` messages.
        ///   - deserializer: A deserializer for `Proto_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func put<Result>(
            request: GRPCCore.ClientRequest<Proto_PutRequest>,
            serializer: some GRPCCore.MessageSerializer<Proto_PutRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Proto_Empty>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Proto_Empty>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Proto_KV.Method.Put.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Proto_KV.ClientProtocol {
    /// Call the "Get" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Proto_GetRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func get<Result>(
        request: GRPCCore.ClientRequest<Proto_GetRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Proto_GetResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.get(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Proto_GetRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Proto_GetResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Put" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Proto_PutRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func put<Result>(
        request: GRPCCore.ClientRequest<Proto_PutRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Proto_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.put(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Proto_PutRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Proto_Empty>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Proto_KV.ClientProtocol {
    /// Call the "Get" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func get<Result>(
        _ message: Proto_GetRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Proto_GetResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Proto_GetRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.get(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Put" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func put<Result>(
        _ message: Proto_PutRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Proto_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Proto_PutRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.put(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}