# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/kv.proto

require 'google/protobuf'


descriptor_data = "\n\x0eproto/kv.proto\x12\x05proto\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\x0c\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x07\n\x05\x45mpty2Z\n\x02KV\x12,\n\x03Get\x12\x11.proto.GetRequest\x1a\x12.proto.GetResponse\x12&\n\x03Put\x12\x11.proto.PutRequest\x1a\x0c.proto.EmptyB=Z;github.com/provide-io/pyvider-rpcplugin/examples/grpc/protob\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Proto
  GetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.GetRequest").msgclass
  GetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.GetResponse").msgclass
  PutRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.PutRequest").msgclass
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Empty").msgclass
end
