# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import sqlite_pb2 as sqlite__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sqlite_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimpleSQLStoreStub(object):
    """Service definition for interacting with a SimpleSQL database
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteQuery = channel.unary_stream(
                '/proto.SimpleSQLStore/ExecuteQuery',
                request_serializer=sqlite__pb2.QueryRequest.SerializeToString,
                response_deserializer=sqlite__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.CancelQuery = channel.unary_unary(
                '/proto.SimpleSQLStore/CancelQuery',
                request_serializer=sqlite__pb2.CancelQueryRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ExecuteUpdate = channel.unary_unary(
                '/proto.SimpleSQLStore/ExecuteUpdate',
                request_serializer=sqlite__pb2.UpdateRequest.SerializeToString,
                response_deserializer=sqlite__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.BatchExecute = channel.unary_unary(
                '/proto.SimpleSQLStore/BatchExecute',
                request_serializer=sqlite__pb2.BatchRequest.SerializeToString,
                response_deserializer=sqlite__pb2.BatchResponse.FromString,
                _registered_method=True)
        self.ExecuteBulkInsert = channel.unary_unary(
                '/proto.SimpleSQLStore/ExecuteBulkInsert',
                request_serializer=sqlite__pb2.BulkInsertRequest.SerializeToString,
                response_deserializer=sqlite__pb2.BulkInsertResponse.FromString,
                _registered_method=True)
        self.GetSchema = channel.unary_unary(
                '/proto.SimpleSQLStore/GetSchema',
                request_serializer=sqlite__pb2.SchemaRequest.SerializeToString,
                response_deserializer=sqlite__pb2.SchemaResponse.FromString,
                _registered_method=True)
        self.ExplainQueryPlan = channel.unary_unary(
                '/proto.SimpleSQLStore/ExplainQueryPlan',
                request_serializer=sqlite__pb2.ExplainQueryRequest.SerializeToString,
                response_deserializer=sqlite__pb2.ExplainQueryResponse.FromString,
                _registered_method=True)
        self.VacuumDatabase = channel.unary_unary(
                '/proto.SimpleSQLStore/VacuumDatabase',
                request_serializer=sqlite__pb2.VacuumRequest.SerializeToString,
                response_deserializer=sqlite__pb2.VacuumResponse.FromString,
                _registered_method=True)
        self.BackupDatabase = channel.unary_unary(
                '/proto.SimpleSQLStore/BackupDatabase',
                request_serializer=sqlite__pb2.BackupRequest.SerializeToString,
                response_deserializer=sqlite__pb2.BackupResponse.FromString,
                _registered_method=True)
        self.CheckIntegrity = channel.unary_unary(
                '/proto.SimpleSQLStore/CheckIntegrity',
                request_serializer=sqlite__pb2.IntegrityRequest.SerializeToString,
                response_deserializer=sqlite__pb2.IntegrityResponse.FromString,
                _registered_method=True)
        self.GetDatabaseInfo = channel.unary_unary(
                '/proto.SimpleSQLStore/GetDatabaseInfo',
                request_serializer=sqlite__pb2.DatabaseInfoRequest.SerializeToString,
                response_deserializer=sqlite__pb2.DatabaseInfoResponse.FromString,
                _registered_method=True)
        self.PrepareStatement = channel.unary_unary(
                '/proto.SimpleSQLStore/PrepareStatement',
                request_serializer=sqlite__pb2.PrepareStatementRequest.SerializeToString,
                response_deserializer=sqlite__pb2.PrepareStatementResponse.FromString,
                _registered_method=True)
        self.ExecutePreparedStatement = channel.unary_stream(
                '/proto.SimpleSQLStore/ExecutePreparedStatement',
                request_serializer=sqlite__pb2.ExecutePreparedStatementRequest.SerializeToString,
                response_deserializer=sqlite__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.DeletePreparedStatement = channel.unary_unary(
                '/proto.SimpleSQLStore/DeletePreparedStatement',
                request_serializer=sqlite__pb2.DeletePreparedStatementRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.BeginTransaction = channel.unary_unary(
                '/proto.SimpleSQLStore/BeginTransaction',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=sqlite__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.CommitTransaction = channel.unary_unary(
                '/proto.SimpleSQLStore/CommitTransaction',
                request_serializer=sqlite__pb2.TransactionRequest.SerializeToString,
                response_deserializer=sqlite__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.RollbackTransaction = channel.unary_unary(
                '/proto.SimpleSQLStore/RollbackTransaction',
                request_serializer=sqlite__pb2.TransactionRequest.SerializeToString,
                response_deserializer=sqlite__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.GetTransactionState = channel.unary_unary(
                '/proto.SimpleSQLStore/GetTransactionState',
                request_serializer=sqlite__pb2.TransactionRequest.SerializeToString,
                response_deserializer=sqlite__pb2.TransactionStateResponse.FromString,
                _registered_method=True)
        self.CreateConnection = channel.unary_unary(
                '/proto.SimpleSQLStore/CreateConnection',
                request_serializer=sqlite__pb2.ConnectionRequest.SerializeToString,
                response_deserializer=sqlite__pb2.ConnectionResponse.FromString,
                _registered_method=True)
        self.CloseConnection = channel.unary_unary(
                '/proto.SimpleSQLStore/CloseConnection',
                request_serializer=sqlite__pb2.ConnectionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class SimpleSQLStoreServicer(object):
    """Service definition for interacting with a SimpleSQL database
    """

    def ExecuteQuery(self, request, context):
        """Query execution
        Execute a query and stream results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelQuery(self, request, context):
        """Cancel an ongoing query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteUpdate(self, request, context):
        """Execute a non-SELECT statement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchExecute(self, request, context):
        """Execute multiple queries/updates in a batch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteBulkInsert(self, request, context):
        """Perform bulk inserts into a table
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchema(self, request, context):
        """Retrieve schema details for a table
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainQueryPlan(self, request, context):
        """Provide query plan for debugging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VacuumDatabase(self, request, context):
        """Perform database vacuum
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BackupDatabase(self, request, context):
        """Create a backup of the database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckIntegrity(self, request, context):
        """Check database integrity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatabaseInfo(self, request, context):
        """Retrieve database metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareStatement(self, request, context):
        """Statement preparation and execution
        Prepare a SQL statement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutePreparedStatement(self, request, context):
        """Execute a prepared statement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePreparedStatement(self, request, context):
        """Clean up prepared statement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BeginTransaction(self, request, context):
        """Transaction management
        Start a new transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitTransaction(self, request, context):
        """Commit the active transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackTransaction(self, request, context):
        """Rollback the active transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionState(self, request, context):
        """Get the current transaction state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateConnection(self, request, context):
        """Connection management
        Establish a new connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseConnection(self, request, context):
        """Close an active connection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimpleSQLStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteQuery': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteQuery,
                    request_deserializer=sqlite__pb2.QueryRequest.FromString,
                    response_serializer=sqlite__pb2.QueryResponse.SerializeToString,
            ),
            'CancelQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelQuery,
                    request_deserializer=sqlite__pb2.CancelQueryRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ExecuteUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteUpdate,
                    request_deserializer=sqlite__pb2.UpdateRequest.FromString,
                    response_serializer=sqlite__pb2.UpdateResponse.SerializeToString,
            ),
            'BatchExecute': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchExecute,
                    request_deserializer=sqlite__pb2.BatchRequest.FromString,
                    response_serializer=sqlite__pb2.BatchResponse.SerializeToString,
            ),
            'ExecuteBulkInsert': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteBulkInsert,
                    request_deserializer=sqlite__pb2.BulkInsertRequest.FromString,
                    response_serializer=sqlite__pb2.BulkInsertResponse.SerializeToString,
            ),
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=sqlite__pb2.SchemaRequest.FromString,
                    response_serializer=sqlite__pb2.SchemaResponse.SerializeToString,
            ),
            'ExplainQueryPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainQueryPlan,
                    request_deserializer=sqlite__pb2.ExplainQueryRequest.FromString,
                    response_serializer=sqlite__pb2.ExplainQueryResponse.SerializeToString,
            ),
            'VacuumDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.VacuumDatabase,
                    request_deserializer=sqlite__pb2.VacuumRequest.FromString,
                    response_serializer=sqlite__pb2.VacuumResponse.SerializeToString,
            ),
            'BackupDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.BackupDatabase,
                    request_deserializer=sqlite__pb2.BackupRequest.FromString,
                    response_serializer=sqlite__pb2.BackupResponse.SerializeToString,
            ),
            'CheckIntegrity': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckIntegrity,
                    request_deserializer=sqlite__pb2.IntegrityRequest.FromString,
                    response_serializer=sqlite__pb2.IntegrityResponse.SerializeToString,
            ),
            'GetDatabaseInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatabaseInfo,
                    request_deserializer=sqlite__pb2.DatabaseInfoRequest.FromString,
                    response_serializer=sqlite__pb2.DatabaseInfoResponse.SerializeToString,
            ),
            'PrepareStatement': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareStatement,
                    request_deserializer=sqlite__pb2.PrepareStatementRequest.FromString,
                    response_serializer=sqlite__pb2.PrepareStatementResponse.SerializeToString,
            ),
            'ExecutePreparedStatement': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecutePreparedStatement,
                    request_deserializer=sqlite__pb2.ExecutePreparedStatementRequest.FromString,
                    response_serializer=sqlite__pb2.QueryResponse.SerializeToString,
            ),
            'DeletePreparedStatement': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePreparedStatement,
                    request_deserializer=sqlite__pb2.DeletePreparedStatementRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'BeginTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginTransaction,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=sqlite__pb2.TransactionResponse.SerializeToString,
            ),
            'CommitTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitTransaction,
                    request_deserializer=sqlite__pb2.TransactionRequest.FromString,
                    response_serializer=sqlite__pb2.TransactionResponse.SerializeToString,
            ),
            'RollbackTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackTransaction,
                    request_deserializer=sqlite__pb2.TransactionRequest.FromString,
                    response_serializer=sqlite__pb2.TransactionResponse.SerializeToString,
            ),
            'GetTransactionState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionState,
                    request_deserializer=sqlite__pb2.TransactionRequest.FromString,
                    response_serializer=sqlite__pb2.TransactionStateResponse.SerializeToString,
            ),
            'CreateConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConnection,
                    request_deserializer=sqlite__pb2.ConnectionRequest.FromString,
                    response_serializer=sqlite__pb2.ConnectionResponse.SerializeToString,
            ),
            'CloseConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseConnection,
                    request_deserializer=sqlite__pb2.ConnectionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.SimpleSQLStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.SimpleSQLStore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimpleSQLStore(object):
    """Service definition for interacting with a SimpleSQL database
    """

    @staticmethod
    def ExecuteQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.SimpleSQLStore/ExecuteQuery',
            sqlite__pb2.QueryRequest.SerializeToString,
            sqlite__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/CancelQuery',
            sqlite__pb2.CancelQueryRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/ExecuteUpdate',
            sqlite__pb2.UpdateRequest.SerializeToString,
            sqlite__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchExecute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/BatchExecute',
            sqlite__pb2.BatchRequest.SerializeToString,
            sqlite__pb2.BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteBulkInsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/ExecuteBulkInsert',
            sqlite__pb2.BulkInsertRequest.SerializeToString,
            sqlite__pb2.BulkInsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/GetSchema',
            sqlite__pb2.SchemaRequest.SerializeToString,
            sqlite__pb2.SchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainQueryPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/ExplainQueryPlan',
            sqlite__pb2.ExplainQueryRequest.SerializeToString,
            sqlite__pb2.ExplainQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VacuumDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/VacuumDatabase',
            sqlite__pb2.VacuumRequest.SerializeToString,
            sqlite__pb2.VacuumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BackupDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/BackupDatabase',
            sqlite__pb2.BackupRequest.SerializeToString,
            sqlite__pb2.BackupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckIntegrity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/CheckIntegrity',
            sqlite__pb2.IntegrityRequest.SerializeToString,
            sqlite__pb2.IntegrityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDatabaseInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/GetDatabaseInfo',
            sqlite__pb2.DatabaseInfoRequest.SerializeToString,
            sqlite__pb2.DatabaseInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareStatement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/PrepareStatement',
            sqlite__pb2.PrepareStatementRequest.SerializeToString,
            sqlite__pb2.PrepareStatementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecutePreparedStatement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.SimpleSQLStore/ExecutePreparedStatement',
            sqlite__pb2.ExecutePreparedStatementRequest.SerializeToString,
            sqlite__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePreparedStatement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/DeletePreparedStatement',
            sqlite__pb2.DeletePreparedStatementRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BeginTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/BeginTransaction',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sqlite__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/CommitTransaction',
            sqlite__pb2.TransactionRequest.SerializeToString,
            sqlite__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/RollbackTransaction',
            sqlite__pb2.TransactionRequest.SerializeToString,
            sqlite__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/GetTransactionState',
            sqlite__pb2.TransactionRequest.SerializeToString,
            sqlite__pb2.TransactionStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/CreateConnection',
            sqlite__pb2.ConnectionRequest.SerializeToString,
            sqlite__pb2.ConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SimpleSQLStore/CloseConnection',
            sqlite__pb2.ConnectionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
