// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: kv.proto

import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf

// MARK: - KV (Server)

/// To build a server, implement a class that conforms to this protocol.
public protocol KVProvider: CallHandlerProvider {
    var interceptors: KVServerInterceptorFactoryProtocol? { get }

    func get(request: GetRequest, context: StatusOnlyCallContext) -> EventLoopFuture<GetResponse>
    func put(request: PutRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Empty>
}

extension KVProvider {
    public var serviceName: Substring {
        return KVServerMetadata.serviceDescriptor.fullName[...]
    }

    /// Determines, calls and returns the appropriate request handler, depending on the request's method.
    public func handle(
        method name: Substring,
        context: CallHandlerContext
    ) -> GRPCServerHandlerProtocol? {
        switch name {
        case "Get":
            return UnaryServerHandler(
                context: context,
                requestDeserializer: ProtobufDeserializer<GetRequest>(),
                responseSerializer: ProtobufSerializer<GetResponse>(),
                interceptors: self.interceptors?.makeGetInterceptors() ?? [],
                userFunction: self.get(request:context:)
            )
        case "Put":
            return UnaryServerHandler(
                context: context,
                requestDeserializer: ProtobufDeserializer<PutRequest>(),
                responseSerializer: ProtobufSerializer<Empty>(),
                interceptors: self.interceptors?.makePutInterceptors() ?? [],
                userFunction: self.put(request:context:)
            )
        default:
            return nil
        }
    }
}

/// Server metadata for KV service
public enum KVServerMetadata {
    public static let serviceDescriptor = GRPCServiceDescriptor(
        name: "KV",
        fullName: "proto.KV",
        methods: [
            GRPCMethodDescriptor(
                name: "Get",
                path: "/proto.KV/Get",
                type: .unary
            ),
            GRPCMethodDescriptor(
                name: "Put",
                path: "/proto.KV/Put",
                type: .unary
            ),
        ]
    )
}

/// Server interceptor factory protocol for KV service
public protocol KVServerInterceptorFactoryProtocol: Sendable {
    func makeGetInterceptors() -> [ServerInterceptor<GetRequest, GetResponse>]
    func makePutInterceptors() -> [ServerInterceptor<PutRequest, Empty>]
}

// MARK: - KV (Client)

/// KV client protocol
public protocol KVClientProtocol: GRPCClient {
    var serviceName: String { get }
    var interceptors: KVClientInterceptorFactoryProtocol? { get }

    func get(
        _ request: GetRequest,
        callOptions: CallOptions?
    ) -> UnaryCall<GetRequest, GetResponse>

    func put(
        _ request: PutRequest,
        callOptions: CallOptions?
    ) -> UnaryCall<PutRequest, Empty>
}

extension KVClientProtocol {
    public var serviceName: String {
        return "proto.KV"
    }

    public func get(
        _ request: GetRequest,
        callOptions: CallOptions? = nil
    ) -> UnaryCall<GetRequest, GetResponse> {
        return self.makeUnaryCall(
            path: KVClientMetadata.Methods.get.path,
            request: request,
            callOptions: callOptions ?? self.defaultCallOptions,
            interceptors: self.interceptors?.makeGetInterceptors() ?? []
        )
    }

    public func put(
        _ request: PutRequest,
        callOptions: CallOptions? = nil
    ) -> UnaryCall<PutRequest, Empty> {
        return self.makeUnaryCall(
            path: KVClientMetadata.Methods.put.path,
            request: request,
            callOptions: callOptions ?? self.defaultCallOptions,
            interceptors: self.interceptors?.makePutInterceptors() ?? []
        )
    }
}

/// KV client implementation
public final class KVNIOClient: KVClientProtocol {
    public let channel: GRPCChannel
    public var defaultCallOptions: CallOptions
    public var interceptors: KVClientInterceptorFactoryProtocol?

    public init(
        channel: GRPCChannel,
        defaultCallOptions: CallOptions = CallOptions(),
        interceptors: KVClientInterceptorFactoryProtocol? = nil
    ) {
        self.channel = channel
        self.defaultCallOptions = defaultCallOptions
        self.interceptors = interceptors
    }
}

/// Client metadata for KV service
public enum KVClientMetadata {
    public enum Methods {
        public static let get = GRPCMethodDescriptor(
            name: "Get",
            path: "/proto.KV/Get",
            type: .unary
        )
        public static let put = GRPCMethodDescriptor(
            name: "Put",
            path: "/proto.KV/Put",
            type: .unary
        )
    }
}

/// Client interceptor factory protocol for KV service
public protocol KVClientInterceptorFactoryProtocol: Sendable {
    func makeGetInterceptors() -> [ClientInterceptor<GetRequest, GetResponse>]
    func makePutInterceptors() -> [ClientInterceptor<PutRequest, Empty>]
}
