# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/kv.proto for package 'proto'
# Original file comments:
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
#

require 'grpc'
require 'proto/kv_pb'

module Proto
  module KV
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'proto.KV'

      rpc :Get, ::Proto::GetRequest, ::Proto::GetResponse
      rpc :Put, ::Proto::PutRequest, ::Proto::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
